---
title: "crimes-boston"
author: "SaiNagaChandraVivekGarimella"
date: "August 15, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(maps)
crime1<-read.csv("C:/Users/garim/OneDrive/Desktop/NEU/Introduction to Data Management and Processing/data sets/crimes-in-boston/crime.csv")
crime1<-drop_na(crime1)

sort <- crime1 %>% group_by(STREET) %>% summarise(complaints=n()) %>% arrange(desc(complaints)) %>% top_n(5)
crime<-left_join(sort,crime1)

 
one<-crime %>% group_by(STREET) %>% summarise(cnt=n())

#per Street
crime %>% group_by(STREET) %>% summarise(cases=n()) %>% ggplot(mapping = aes(x=STREET,y=cases))+geom_bar(stat = 'identity')+coord_flip()

#locations
corners<-map_data('state',region='massachusetts')
ggplot(corners)+geom_polygon(mapping = aes(x=long,y=lat),fill=NA,color="black") +geom_point(data=crime,mapping = aes(x=Long,y=Lat,color=STREET))+coord_cartesian(xlim = c(-71,-71.2) ,ylim=c(42.22, 42.37))

#offnese per year
yearr <-crime %>% group_by(STREET,YEAR) %>% summarise(cases_filed_per_year=n())

left_join(one,yearr) %>% ggplot(mapping = aes(x=STREET,y=cases_filed_per_year,fill=as.factor(YEAR)))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()+labs(fill='YEARS')

#oofense per month
month<-crime %>% group_by(STREET,MONTH) %>% summarise(cases_filed_per_month=n()) %>% arrange(desc(cases_filed_per_month)) %>% group_by(STREET) %>% top_n(3)
left_join(one,month) %>% ggplot(mapping = aes(x=STREET,y=cases_filed_per_month,fill=as.factor(MONTH)))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()+labs(fill='MONTHS')


#offense code group per day of week
day<-crime %>% group_by(STREET,DAY_OF_WEEK) %>% summarise(days=n())
left_join(one,day) %>% ggplot(mapping = aes(x=STREET,y=days,fill=DAY_OF_WEEK))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()

#crime on date
crime[['OCCURRED_ON_DATE']]<-crime[['OCCURRED_ON_DATE']] %>% str_sub(9,10)
dates_occurred<- crime %>% group_by(STREET,OCCURRED_ON_DATE) %>% summarise(dates=n()) %>% arrange(desc(dates)) %>% group_by(STREET) %>% top_n(3)
left_join(one,dates_occurred) %>% ggplot(mapping = aes(x=STREET,y=dates,fill=OCCURRED_ON_DATE))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()

#offense per hour
hour<-crime %>% group_by(STREET,HOUR) %>% summarise(cases_filed_per_hour=n()) %>% arrange(desc(cases_filed_per_hour)) %>% group_by(STREET) %>% top_n(3)
left_join(one,hour) %>% ggplot(mapping = aes(x=STREET,y=cases_filed_per_hour,fill=as.factor(HOUR)))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()+labs(fill='HOURS')



#OFFENSE CODE GROUP per street
two<-crime %>% group_by(STREET,OFFENSE_CODE_GROUP) %>% summarise(tot=n())

left_join(one,two) %>% mutate(new=tot/cnt) %>% arrange(desc(tot)) %>% group_by(STREET) %>% top_n(5) %>% ggplot(mapping = aes(x=STREET,y=new,fill=OFFENSE_CODE_GROUP))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()



#offense code group per reporting area
area<-crime %>% group_by(STREET,REPORTING_AREA) %>% summarise(cases_filed_per_area=n()) %>% arrange(desc(cases_filed_per_area)) %>% group_by(STREET) %>% top_n(5)

left_join(one,area) %>% ggplot(mapping = aes(x=STREET,y=cases_filed_per_area,fill=as.factor(REPORTING_AREA)))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()+labs(fill='REPORTING AREAS')


#ucr noted per street
uucr<-crime %>% group_by(STREET,UCR_PART) %>% summarise(ucr_level=n())
left_join(one,uucr) %>% filter(UCR_PART!="")%>% ggplot(mapping = aes(x=STREET,y=ucr_level,fill=UCR_PART))+geom_bar(stat = 'identity',position = 'dodge')+coord_flip()





```

